import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Sidebar from '@/components/Sidebar'
import Feed from '@/components/Feed'
import Widgets from '@/components/Widgets'


const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>twitter-v4</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' flex max-w-6xl mx-auto min-h-screen'>
        {/*SideBar*/ }
        <Sidebar  />

        {/*Feed*/ }
        <Feed />
        
        {/*Widgets*/ }
        <Widgets />
      </main>
    </>
  )
}
