import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import Sidebar from '@/components/Sidebar'
import Feed from '@/components/Feed'
import Widgets from '@/components/Widgets'


const inter = Inter({ subsets: ['latin'] })

export default function Home({allNews,randomUserResults}) {
  return (
    <>
      <Head>
        <title>twitter-v4</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=' flex  mx-auto min-h-screen'>
        {/*SideBar*/ }
        <Sidebar  />

        {/*Feed*/ }
        <Feed />
        
        {/*Widgets*/ }
        
        <Widgets articles={allNews.articles} randomUserResults={randomUserResults.results} />
      </main>
    </>
  )
}

export async function getServerSideProps(){
  const newResults=await fetch("https://saurav.tech/NewsAPI/top-headlines/category/business/us.json")
                        .then(response => response.json())

  //who to fallow section
  const randomUserResults=await fetch("https://randomuser.me/api/?results=50&inc=name,login,picture")
                          .then(response => response.json())

  return{
    props:{allNews:newResults,randomUserResults}
  }
}
